Allow escaping curly braces in setenv
tox-dev/tox pull request #1656
Opened 2020-08-19 23:21 UTC by mkenigs

Currently braces can be escaped, but the backslashes are not removed,
making it impossible to add a plain curly brace

## Contribution checklist:

(also see [CONTRIBUTING.rst](../tree/master/CONTRIBUTING.rst) for details)

- [x] wrote descriptive pull request text
- [ ] added/updated test(s)
- [ ] updated/extended the documentation
- [x] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [ ] added news fragment in [changelog folder](../tree/master/docs/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`,`breaking`, `doc`, `misc`
  * if PR has no issue: consider creating one first or change it to the PR number after creating the PR
  * "sign" fragment with "by :user:`<your username>`"
  * please use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files - by :user:`superuser`."
  * also see [examples](../tree/master/docs/changelog)
- [ ] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

2020-08-20 10:05 UTC, gaborbernat requested changes
Needs changelog and test.

2020-08-20 12:09 UTC, mkenigs commented
Should this be done after every time _replace is called or moved into _replace?

2020-08-31 16:46 UTC, mkenigs commented
@gaborbernat anything else needed for this?

2020-08-31 18:36 UTC, merged

2020-09-01 17:45 UTC, gaborbernat commented
Released via https://pypi.org/project/tox/3.20.0/