Bracketed escaping
tox-dev/tox pull request #1709
Opened 2020-10-22 14:02 UTC by jayvdb

Fixes https://github.com/tox-dev/tox/issues/1708

## Contribution checklist:

(also see [CONTRIBUTING.rst](../tree/master/CONTRIBUTING.rst) for details)

- [ ] wrote descriptive pull request text
- [x] added/updated test(s)
- [ ] updated/extended the documentation
- [ ] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [ ] added news fragment in [changelog folder](../tree/master/docs/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`,`breaking`, `doc`, `misc`
  * if PR has no issue: consider creating one first or change it to the PR number after creating the PR
  * "sign" fragment with "by :user:`<your username>`"
  * please use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files - by :user:`superuser`."
  * also see [examples](../tree/master/docs/changelog)
- [x] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

2020-10-22 14:23 UTC, jayvdb commented on tests/unit/config/test_config.py
> +        # assert envconfig.setenv["FOO"] == "a{b c}d"
highlighting this as what fails with the incomplete implementation.

2020-10-23 06:33 UTC, gaborbernat commented
> Adds `{\}`, `{{}` and `{}}` as an escaping mechanism in settings.
> 
> `{{}` and `{}}` are not implemented so they can be used safely together.
> Additional coding is needed to handle values from the engine being pushed
> back into the engine, so they are re-escape

I would prefer not to introduce new ways of doing things. As such only ``\`` character I'm interested in supporting, I don't agree with supporting ``{{`` or ``}}`` 🤔

2020-10-23 06:54 UTC, jayvdb commented
> I don't agree with supporting `{{` or `}}`

I am also not convinced about adding those; I've tried to lay out the problems at

https://github.com/tox-dev/tox/issues/1708

That commit in this PR is mostly to show where the problem exists, so anyone can play with it if they think it is easy to solve.

2020-10-24 08:09 UTC, gaborbernat requested changes
This now has merge conflicts.

2020-10-27 08:21 UTC, gaborbernat commented
@jayvdb this is merge conflicting.

2020-11-07 10:01 UTC, gaborbernat commented
I'll close this for now until you can attend to the PR again. Once you've done we can reopen.

2020-11-07 10:01 UTC, closed without merging