Make the passenv environment setting case sensitive
tox-dev/tox pull request #1718
Opened 2020-10-25 23:38 UTC by gnikonorov

## Description
Make the `passenv` environment setting case sensitive. Before this change it was including all environment variables that matched in a case insensitive fashion ( `FOO` included `FOO`, `fOo`, and `foo` for example )

Closes https://github.com/tox-dev/tox/issues/1534

## Contribution checklist:

(also see [CONTRIBUTING.rst](../tree/master/CONTRIBUTING.rst) for details)

- [x] wrote descriptive pull request text
- [x] added/updated test(s)
- [x] updated/extended the documentation - Not applicable in this case 
- [x] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [x] added news fragment in [changelog folder](../tree/master/docs/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`,`breaking`, `doc`, `misc`
  * if PR has no issue: consider creating one first or change it to the PR number after creating the PR
  * "sign" fragment with "by :user:`<your username>`"
  * please use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files - by :user:`superuser`."
  * also see [examples](../tree/master/docs/changelog)
- [x] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

2020-10-25 23:42 UTC, asottile commented
at least on posix this is incorrect, `A` and `a` are two separate environment variables:

```console
$ a=1 A=2 env | grep -i '^a='
A=2
a=1
```

2020-10-25 23:43 UTC, asottile commented
on windows however, `a` and `A` are the same variable:

```
C:\Users\Anthony>set A=1

C:\Users\Anthony>set a=2

C:\Users\Anthony>echo %A% %a%
2 2
```

2020-10-25 23:45 UTC, gnikonorov commented
> on windows however, `a` and `A` are the same variable:
> 
> ```
> C:\Users\Anthony>set A=1
> 
> C:\Users\Anthony>set a=2
> 
> C:\Users\Anthony>echo %A% %a%
> 2 2
> ```

Thank you @asottile. I forgot about Windows. I'll add an exclusion for it.

2020-10-25 23:47 UTC, asottile commented
I'm 50/50 on whether we should change this, or whether we should just document it as case insensitive

2020-10-25 23:49 UTC, gnikonorov commented
Since this is my first time opening a PR in this repo, I'll defer to more experienced committers. Thoughts @gaborbernat ( since we spoke on the linked issue ) ?

2020-10-26 07:11 UTC, gaborbernat requested changes
> FWIW I think it would be easy and clean enough to just uppercase `name` and `spec` if `platform.system() == "Windows":`

Yeah, on Windows we need to be the case insensitive.

2020-10-26 15:49 UTC, asottile commented
On second thought, changing this behaviour is likely to break a lot of people [even tox itself](https://github.com/tox-dev/tox/blob/c5a10d730e562164b03f2669596e0168ba9b3aac/tox.ini#L25-L27)

I'm leaning more towards not changing the behaviour and just documenting the case insensitivity

2020-10-26 15:58 UTC, gnikonorov commented
> On second thought, changing this behaviour is likely to break a lot of people [even tox itself](https://github.com/tox-dev/tox/blob/c5a10d730e562164b03f2669596e0168ba9b3aac/tox.ini#L25-L27)
> 
> 
> 
> I'm leaning more towards not changing the behaviour and just documenting the case insensitivity

At the very least, it sounds like a major version bump

2020-10-27 08:20 UTC, gaborbernat commented
Ok. Let's not address here in the code. But document the behavior.

2020-10-27 08:20 UTC, closed without merging