Add a test for #1928
tox-dev/tox pull request #1934
Opened 2021-03-01 15:11 UTC by hexagonrecursion

See #1928

This PR does not fix the bug. It only adds a test for it. Note: this PR currently includes https://github.com/tox-dev/tox/pull/1930 because otherwise CI fails

## Contribution checklist:

- [x] wrote descriptive pull request text
- [x] added/updated test(s)
- [ ] updated/extended the documentation - N/A
- [ ] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/) - N/A
      in message body
- [ ] added news fragment in [changelog folder](../tree/master/docs/changelog) - will add after I open the PR
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`,`breaking`, `doc`, `misc`
  * if PR has no issue: consider creating one first or change it to the PR number after creating the PR
  * "sign" fragment with "by :user:`<your username>`"
  * please use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files - by :user:`superuser`."
  * also see [examples](../tree/master/docs/changelog)
- [ ] added yourself to `CONTRIBUTORS` (preserving alphabetical order) - CONTRIBUTORS: No such file or directory

2021-03-01 15:13 UTC, hexagonrecursion commented
Since this PR does not fix the bug there is no user-visible change. Does it need a changelog entry?

2021-03-01 15:15 UTC, gaborbernat requested changes

2021-03-01 15:15 UTC, gaborbernat commented on setup.cfg
> +    pyramid<2  # workaround for https://github.com/devpi/devpi/issues/835
Backdoor PR?

2021-03-01 15:15 UTC, hexagonrecursion commented on setup.cfg
> +    pyramid<2  # workaround for https://github.com/devpi/devpi/issues/835
> Note: this PR currently includes #1930 because otherwise CI fails

2021-03-01 15:17 UTC, gaborbernat commented on setup.cfg
> +    pyramid<2  # workaround for https://github.com/devpi/devpi/issues/835
Let's wait until upstream releases a fix.

2021-03-01 15:17 UTC, gaborbernat commented on tests/bug/test_gh_1928.py
> +import json
Please don't introduce a new layout pattern that goes against what the project already has in place. Also, I don't believe in the test only PRs, so would prefer to feature with test together.

2021-03-01 15:20 UTC, gaborbernat commented on tests/bug/test_gh_1928.py
> +import json
This should go and follow the existing ``{posargs}`` syntax from https://github.com/tox-dev/tox/blob/rewrite/tests/config/loader/ini/replace/test_replace_posargs.py

2021-03-02 05:25 UTC, hexagonrecursion commented
> Please don't introduce a new layout pattern that goes against what the project already has in place. Also, I don't believe in the test only PRs, so would prefer to feature with test together.

OK. back to the drawing board

2021-03-02 05:25 UTC, closed without merging