Fix usedevelop without setup.py
tox-dev/tox pull request #2198
Opened 2021-09-02 12:54 UTC by AntoineD

Fix #2197 

I was able to check the fix on an external project but unfortunately the new test does not work when the `cmd` fixture is called the second time (error at teardown).
Please let me know how to fix this test or feel free to change it.

2021-09-02 13:22 UTC, gaborbernat requested changes
Not sure how you even get that far.

2021-09-02 13:22 UTC, gaborbernat commented on src/tox/venv.py
> +        if setup_py.exists():
If the setup.py does not exist, this here https://github.com/tox-dev/tox/blob/954399ba18/src/tox/package/builder/legacy.py#L37 will fail earlier

2021-09-02 15:21 UTC, gaborbernat reviewed
If you can make it work for both old and new world I'm happy to accept this PR.

2021-09-02 19:13 UTC, AntoineD commented
What do you mean by *old and new world*?

2021-09-02 22:41 UTC, gaborbernat commented
It should work with any setuptools/pip version the user might use.

2021-09-07 18:11 UTC, AntoineD commented
It seems to me that it does not worth the effort then, as compared to creating an almost empty `setup.py`.

2021-09-07 18:11 UTC, closed without merging