Let tox run fail when all envs are skipped
tox-dev/tox pull request #2206
Opened 2021-09-08 17:41 UTC by jugmac00

fixes #2195

- [x] wrote descriptive pull request text
- [x] added/updated test(s)
- [ ] updated/extended the documentation
- [x] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [x] added news fragment in [changelog folder](../tree/master/docs/changelog)

2021-09-09 09:55 UTC, gaborbernat requested changes

2021-09-09 09:55 UTC, gaborbernat commented on tests/session/cmd/test_sequential.py
> +    # tox run fails as all envs are skipped
Put the comment to the right side of the assert failed 👍

2021-09-09 09:55 UTC, gaborbernat commented on src/tox/session/cmd/run/common.py
>          duration_individual = [o.elapsed for o in run.outcomes]
IMHO a better way to express this, and reads better (no longer needed your comment), is to do:

```python
    successful, skipped = [], []
    for run in runs:
        successful.append(run.code == Outcome.OK or run.ignore_outcome) 
        skipped.append(run.skipped)
        duration_individual = [o.elapsed for o in run.outcomes]
     ...

    all_good = all(successful) and not all(skipped)
    if all_good:
       ...
```

2021-09-09 10:30 UTC, jugmac00 commented
@gaborbernat Thanks for the review!

2021-09-10 08:00 UTC, gaborbernat approved these changes

2021-09-10 08:00 UTC, merged