Only respect ALL environments when not in parallel
tox-dev/tox pull request #2207
Opened 2021-09-09 06:53 UTC by guahki

fixes #2167

## Contribution checklist:

(also see [CONTRIBUTING.rst](../tree/master/CONTRIBUTING.rst) for details)

- [ ] wrote descriptive pull request text
- [ ] added/updated test(s)
- [ ] updated/extended the documentation
- [x] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [ ] added news fragment in [changelog folder](../tree/master/docs/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`, `breaking`, `doc`, `misc`
  * if PR has no issue: consider creating one first or change it to the PR number after creating the PR
  * "sign" fragment with ```-- by :user:`<your username>`.```
  * please, use full sentences with correct case and punctuation, for example:
    ```rst
    Fixed an issue with non-ascii contents in doctest text files -- by :user:`superuser`.
    ```
  * also see [examples](../tree/master/docs/changelog)
- [ ] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

2021-09-09 06:53 UTC, guahki commented
As

1. this is my first contribution to this project and
1. I'm not sure about the correct way to fix this

this is kind of a draft/request PR. I will happily create appropriate changelog when you tell me, this is a sensible way of fixing the problem.

Thanks for the awesome ``tox`` tool!

2021-09-09 08:11 UTC, guahki commented on src/tox/config/__init__.py
> +        ) and not os.environ.get(PARALLEL_ENV_VAR_KEY_PRIVATE):
Maybe one just wants to check for

```suggestion
        ) and PARALLEL_ENV_VAR_KEY_PRIVATE not in os.environ:
```

2021-09-09 09:36 UTC, gaborbernat requested changes
Can you please add changelog and test for this?

2021-09-09 13:41 UTC, guahki commented
I added the changelog.

Unfortunately I do not have the time to write a test right now. I would be happy, if anybody can assist with this.

2021-09-13 11:33 UTC, guahki commented
I had a look into it and it wasn't that hard indeed.
Thanks for your patience!

2021-09-13 19:17 UTC, gaborbernat approved these changes

2021-09-13 19:17 UTC, merged