Do not reinstall in develop mode without setup.py
tox-dev/tox pull request #2273
Opened 2021-11-13 16:55 UTC by VincentVanlaer

The detection logic for figuring out whether a editable install needs to be reinstalled only works for setuptools based builds using setup.py. If setup.py cannot be found the code will fail with an invocation error. Currently no standard mechanism exists to query a package installed in editable mode whether it should be reinstalled or not. Hence, this change skips reinstallation if setup.py cannot be found.

Fixes #2197 

## Contribution checklist:

(also see [CONTRIBUTING.rst](../tree/master/CONTRIBUTING.rst) for details)

- [x] wrote descriptive pull request text
- [x] added/updated test(s)
- [x] updated/extended the documentation
- [x] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [x] added news fragment in [changelog folder](../tree/master/docs/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`, `breaking`, `doc`, `misc`
  * if PR has no issue: consider creating one first or change it to the PR number after creating the PR
  * "sign" fragment with ```-- by :user:`<your username>`.```
  * please, use full sentences with correct case and punctuation, for example:
    ```rst
    Fixed an issue with non-ascii contents in doctest text files -- by :user:`superuser`.
    ```
  * also see [examples](../tree/master/docs/changelog)
- [x] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

2021-11-16 09:06 UTC, gaborbernat requested changes
Blocked until the CI passes.

2021-11-17 18:57 UTC, VincentVanlaer commented
It seems the CI fails because python < 3.7 is not available anymore in the macos azure images, not really something I can do anything about except for just disabling these tests.

2021-11-17 18:59 UTC, gaborbernat commented
Yeah, we'll need to migrate to Github Actions, this PR will need to wait for that. Also, I'll be on holiday until the 3rd of December, so unless @asottile picks it up we'll not move on this, sorry. But we've put it in the queue.

2021-11-25 12:11 UTC, ssbarnea commented
I can help with GHA issue but I will still need someone to merge the fixes.

2021-12-29 00:20 UTC, gaborbernat approved these changes

2021-12-29 00:20 UTC, merged