doc: fix typo in description of tox-conda plugin
tox-dev/tox pull request #2363
Opened 2022-03-02 20:41 UTC by vladdoster

## Thanks for contributing a pull request!

If you are contributing for the first time or provide a trivial fix don't worry too
much about the checklist - we will help you get started.

## Contribution checklist:

(also see [CONTRIBUTING.rst](../tree/master/CONTRIBUTING.rst) for details)

- [x] wrote descriptive pull request text
- [x] added/updated test(s)
- [x] updated/extended the documentation
- [x] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [x] added news fragment in [changelog folder](../tree/master/docs/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`, `breaking`, `doc`, `misc`
  * if PR has no issue: consider creating one first or change it to the PR number after creating the PR
  * "sign" fragment with ```-- by :user:`<your username>`.```
  * please, use full sentences with correct case and punctuation, for example:
    ```rst
    Fixed an issue with non-ascii contents in doctest text files -- by :user:`superuser`.
    ```
  * also see [examples](../tree/master/docs/changelog)
- [x] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

2022-03-02 21:52 UTC, jugmac00 requested changes
Hey @vladdoster 

Thanks for the typo fix.

For this simple fix we do not need a changelog. Could you please delete it? Then we are good to merge.

Thanks

2022-03-04 09:28 UTC, gaborbernat requested changes

2022-03-04 09:28 UTC, gaborbernat commented on docs/changelog/2364.doc.rst
> +Correct misspelling of conda in tox-conda plugin description -- by :user:`vladdoster`.
Let's delete this file 👍

2022-03-18 12:06 UTC, gaborbernat requested changes
Seems there's a merge conflict 🤔

2022-04-09 12:20 UTC, merged