Migrate tox 3 documentation
tox-dev/tox pull request #2408
Opened 2022-04-28 15:55 UTC by gaborbernat

This is the first pass.

Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>

2022-04-30 12:09 UTC, jugmac00 requested changes
Thanks a lot!

I had a first pass - mostly from the GitHub ui, and only occasionally on the rendered docs - I will have another one when the PR is finished.

Apart from my inline comments, you certainly noticed that building the documentation is currently broken to an changed anchor in the pytest documentation.

Speaking of the pytest documentation, have you noticed that they restructured their documentation to follow https://diataxis.fr/ documentation framework? (not a technical framework, but a way to structure your docs).

Our documentation looks good, but maybe you have a time to have a look at diataxis whether you like it.

e.g. our faq is not really a faq as I have not seen too many people asking for customizing virtualenv creation - currently our faq is more like a place to put stuff which does not fit anywhere else.

In diataxis these would be all "how-tos". Our user-guide would be a tutorial, `configuration`, `tox cli interface` and `API` would go in a reference section, and so on... 

If we ever would plan to restructure the documentation now would be a great time.

Oh - and I think we need a What's new in tox version4 page - with all highlights.

2022-04-30 12:19 UTC, jugmac00 reviewed
some more comments

2022-04-30 12:19 UTC, jugmac00 commented on docs/faq.rst
> +Customize virtual environment creation
```suggestion
Customizing virtual environment creation
```

2022-04-30 12:19 UTC, jugmac00 commented on docs/faq.rst
> +Build documentation with Sphinx
```suggestion
Building documentation with Sphinx
```

2022-04-30 12:19 UTC, jugmac00 commented on docs/faq.rst
> +Build documentation with mkdocs
```suggestion
Building documentation with mkdocs
```

2022-04-30 13:44 UTC, pradyunsg commented on docs/faq.rst
> +  one.
Pretty much. There's no guarentees around which one pip would use the file from, if it sees two files with the same name from two package indexes.

2022-05-31 15:00 UTC, jugmac00 commented
It looks like cpython is also adoption the Diátaxis framework for documentation:
https://discuss.python.org/t/adopting-the-diataxis-framework-for-python-documentation/15072

https://diataxis.fr/how-to-use-diataxis/
https://diataxis.fr/

I think it would be a great idea to also adopt it.

2022-05-31 15:06 UTC, gaborbernat commented
I'm not against it, but until we have availability for someone (mostly me in the first phase) to work on it, it doesn't really matter 😆

2022-10-25 04:38 UTC, gaborbernat commented
One thing I've learned part of the diatrixis framework is to not do big bang release. Considering that we'll merge this as is and do smaller follow-up PRs to make it diatrixis.

2022-10-25 04:51 UTC, merged