Do no longer recommend pipx-in-pipx
tox-dev/tox pull request #2456
Opened 2022-07-05 08:14 UTC by jugmac00

... as it is no longer actively maintained.

We can trust our users to be able to install pipx in a different way.

2022-07-05 15:12 UTC, gaborbernat requested changes
I never had any issues with it and I don't see any mention of not being maintained. 🤔 I'd rather adopt its maintainership rather than recommend something else 😆

2022-07-05 17:05 UTC, jugmac00 commented
Today I was asked how to install tox and I wanted to direct the op to our documentation but I did not feel comfortable doing so because of pipx-in-pipx.

Whatever you call its current maintenance state, I do think it is enough from our side to recommend pipx - they have their own installation documentation.

2022-07-05 17:10 UTC, gaborbernat commented
> Today I was asked how to install tox and I wanted to direct the op to our documentation but I did not feel comfortable doing so because of pipx-in-pipx.

Guess we disagree on recommending `pipx-in-pipx`. 🤔 

> Whatever you call its current maintenance state, I do think it is enough from our side to recommend pipx - they have their own installation documentation.

Perhaps, but I found people found it helpful to not have to read another documentation on how to get quickly started 🤔

2022-07-06 15:30 UTC, gaborbernat commented
I think we had different experiences. `pipx-in-pipx` worked flawlessly for me on macOS, Arch Linux or Windows. I don't use Ubuntu personally so 🤷

2022-07-06 15:30 UTC, closed without merging