Fix PYTHONPATH passed to envreport / "pip freeze"
tox-dev/tox pull request #2529
Opened 2022-11-03 22:07 UTC by f3flight

Closes #2528
This fix uses the same approach as used for "pip install" (https://github.com/tox-dev/tox/blob/3.27.0/src/tox/venv.py#L432)

2022-11-03 22:13 UTC, gaborbernat requested changes
Needs test.

2022-11-04 19:57 UTC, gaborbernat requested changes

2022-11-04 19:57 UTC, gaborbernat commented on tests/unit/test_venv.py
> +@pytest.mark.parametrize("pythonpath", (None, "blah"))
if we don't add more parameters there's no need for parametrize here; also use mocker.patch from pytest-mock instead imorting unittest.mock

2022-11-14 02:18 UTC, f3flight commented
@gaborbernat would you be able to have another look?

2022-11-14 02:20 UTC, gaborbernat approved these changes

2022-11-14 02:20 UTC, merged