Add missing build test dependency
tox-dev/tox pull request #2577
Opened 2022-12-01 20:32 UTC by ssbarnea

Fixes: #2576

# Thanks for contribution

Please, make sure you address all the checklists (for details on how see
[development documentation](http://tox.readthedocs.org/en/latest/development.html#development))!

- [ ] ran the linter to address style issues (`tox -e fix_lint`)
- [ ] wrote descriptive pull request text
- [ ] ensured there are test(s) validating the fix
- [ ] added news fragment in `docs/changelog` folder
- [ ] updated/extended the documentation

2022-12-01 22:14 UTC, gaborbernat requested changes

2022-12-01 22:14 UTC, gaborbernat commented on pyproject.toml
> +  "build>=0.9.0",
Let's make it `build[virtualenv]` and you can drop trailing .0-s

2022-12-02 18:27 UTC, merged

2022-12-02 18:49 UTC, mgorny commented
Thank you!

2023-01-03 15:05 UTC, ssbarnea commented
@jcristau I do not remember and do not plan to spend my free time investigating it. Feel free to check their changelog and see if there are good or not reasons for the bump.

2023-01-03 15:15 UTC, jcristau commented
I did, and can't see any.
Too bad, thanks anyway.  I guess there was already an unexplained bump in https://github.com/tox-dev/tox/commit/01004234a48a834a8f814b2639b5d78fbc4462a6 so I'll just pin tox to <4.