Fail on blanks in passed env vars
tox-dev/tox pull request #2671
Opened 2022-12-10 08:46 UTC by ericzolf

Avoids to oversee pass_env/passenv going from blank to comma separated list between tox 3 and 4
Resolves https://github.com/tox-dev/tox/issues/2658

(as I create this PR, I allowed myself to fix the `tox -e fix`~_lint~
# Thanks for contribution

Please, make sure you address all the checklists (for details on how see
[development documentation](http://tox.readthedocs.org/en/latest/development.html#development))!

- [x] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [ ] ensured there are test(s) validating the fix
- [ ] added news fragment in `docs/changelog` folder
- [x] updated/extended the documentation

I know that I'm not fully done but I would appreciate first feedback on my code before I pursue, as this is my first PR for this project.

2022-12-10 09:47 UTC, jugmac00 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] ran the linter to address style issues (`tox -e fix`)
Nice catch! This should go in a separate PR.

2022-12-10 09:53 UTC, ericzolf commented
OK, moved to #2672

2022-12-10 16:34 UTC, gaborbernat requested changes

2022-12-10 16:34 UTC, gaborbernat commented on src/tox/tox_env/api.py
> +                    f"blanks like {blank_values}; a comma is possibly missing",
I think you wanted to say here space, not blank lines.

2022-12-10 16:34 UTC, gaborbernat commented on tests/tox_env/test_tox_env_api.py
> +    commands=python -c 'import os; print("MYENV", os.getenv("MYENV"))'""",
We should never get or use these commands, so remove them. Also, let's keep this tox.ini in one line is simple enough for it.

2022-12-10 16:34 UTC, gaborbernat commented on src/tox/tox_env/api.py
> +                    f"blanks like {blank_values}; a comma is possibly missing",
We wrap at 120 characters.

2022-12-10 16:34 UTC, gaborbernat commented on tests/tox_env/test_tox_env_api.py
> +    out = (
We wrap at 120 characters.

2022-12-10 16:34 UTC, gaborbernat commented on tests/tox_env/test_tox_env_api.py
> +    )
Let's not use regex assert, let's do a literal match, please.  So we print just the error message and notthing more.

2022-12-10 16:35 UTC, gaborbernat requested changes

2022-12-11 02:59 UTC, gaborbernat approved these changes

2022-12-11 03:03 UTC, merged