Restore TOX_SKIP_ENV filtering
tox-dev/tox pull request #2707
Opened 2022-12-14 09:16 UTC by mgedmin

This is still documented in docs/config.rst.  The only missing thing is the reporting at verbosity level 2.

I feel bad about the missing reporting.  Could someone help me figure it out?

Fixes #2698.

# Thanks for contribution

Please, make sure you address all the checklists (for details on how see
[development documentation](http://tox.readthedocs.org/en/latest/development.html#development))!

- [x] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [x] ensured there are test(s) validating the fix
- [x] added news fragment in `docs/changelog` folder
- [x] updated/extended the documentation

2022-12-14 09:41 UTC, mgedmin commented
I am very confused about logging levels.  `tox --help` says

```
verbosity:
  every -v increases, every -q decreases verbosity level, default INFO, map 0=CRITICAL|1=ERROR|2=WARNING|3=INFO|4=DEBUG|5=NOTSET

  -v, --verbose               increase verbosity (default: 2)
  -q, --quiet                 decrease verbosity (default: 0)
```

so level 2 is WARNING, and the default level is INFO, which is 3, but also the default level is 2, which is WARNING.

Anyway, I'm logging with .info(), and it's visible only if you pass a single -v to tox, which means the actual default is WARNING and the --help output lies to me?

Should I change the log level of this message to .warning() so it would match docs/config.rst?

2022-12-14 15:23 UTC, gaborbernat requested changes

2022-12-14 15:23 UTC, gaborbernat commented on docs/changelog/2698.bugfix.rst
> +``TOX_SKIP_ENV`` environment variable now works again (it was unintentionally
Please wrap at 120 characters.

2022-12-14 15:23 UTC, gaborbernat commented on tests/session/test_env_select.py
> +        """
You can include this in one line considering its simplicity.

2022-12-14 15:23 UTC, gaborbernat commented on tests/session/test_env_select.py
> +        env_list = py3{10,9},mypy
You can include this in one line considering its simplicity.

2022-12-14 15:23 UTC, gaborbernat commented on src/tox/session/env_select.py
> +        self._warned_about = set()
You can move line 111 here; no need to define and then initialize it here; just initializing it is enough

2022-12-14 15:23 UTC, gaborbernat commented on src/tox/session/env_select.py
> +        tox_env_filter_re = re.compile(tox_env_filter) if tox_env_filter is not None else None
This definition should happen in the constructor of this class, not every time on this call, no?

2022-12-14 15:23 UTC, gaborbernat commented on docs/changelog/2698.bugfix.rst
> +``TOX_SKIP_ENV`` environment variable now works again (it was unintentionally
Also do you want to add your user name here? 

```
- :by:`x`.
```

2022-12-15 02:56 UTC, merged

2022-12-15 11:29 UTC, mgedmin commented
Ah, sorry, I meant to take another look at this but was too busy yesterday.

Thank you for finishing it!

2022-12-15 11:30 UTC, mgedmin commented on src/tox/session/env_select.py
> +    add_to.add_argument("--skip-env", dest="skip_env", metavar="re", help=help_msg, default="", type=str)
I like this even more than the environment variable!