Fix extracting extras from markers with many extras
tox-dev/tox pull request #2792
Opened 2022-12-30 01:23 UTC by q0w

# Thanks for contribution

Please, make sure you address all the checklists (for details on how see
[development documentation](http://tox.readthedocs.org/en/latest/development.html#development))!

- [x] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [x] ensured there are test(s) validating the fix
- [x] added news fragment in `docs/changelog` folder
- [ ] updated/extended the documentation

2022-12-30 01:27 UTC, q0w commented
What should be done with requirements like ` 'sphinx>=3; extra == "extras1" and extra == "extras2"'`
```python
requires = [
        Requirement('filelock<4.0.0,>=3.9.0; extra == "extras1" or extra == "extras2"'),
        Requirement('sphinx>=3; extra == "extras1" and extra == "extras2"')
    ]
    result = dependencies_with_extras(requires, {"extras1"}, "")
```
What result is expected?

2022-12-30 01:31 UTC, q0w commented
Maybe its a bug in a poetry build backend, because setuptools make different METADATA Require-Dists
 ```
Provides-Extra: extras1
Requires-Dist: filelock (<4.0.0,>=3.9.0) ; extra == 'extras1'
Provides-Extra: extras2
Requires-Dist: filelock (<4.0.0,>=3.9.0) ; extra == 'extras2'

2022-12-30 04:43 UTC, gaborbernat commented
> What result is expected?

I'd say only filelock to show up, as sphinx needs both extra enabled.

> Maybe its a bug in the poetry build backend, because setuptools makes different METADATA Requires-Dists

Worth reporting it to them, but I think is valid to expect if something generates such to behave as my previous paragraph here describes. Can you add a test for it?

2022-12-30 04:44 UTC, gaborbernat requested changes

2022-12-30 04:44 UTC, gaborbernat commented on tests/tox_env/python/virtual_env/package/test_python_package_util.py
> +    requires = [Requirement('filelock<4.0.0,>=3.9.0; extra == "extras1" or extra == "extras2"')]
instead of naming it poetry let's just say it `extra_or` :+1: And lets add an `extra_and` variant please?

2022-12-31 00:25 UTC, gaborbernat approved these changes
Let's ship as is and do the `and` handling as a follow-up.

2022-12-31 00:26 UTC, merged

2023-01-01 05:12 UTC, q0w commented
How many logic markers should tox handle? One?