Add more explanation to `list_dependencies_command` configuration option
tox-dev/tox pull request #2883
Opened 2023-01-18 22:57 UTC by Czaki

Whileing debugging different behavior of tests locally and on, CI I noticed thI, installed packages are listed on CI, and when running locally, they are not. 

It make it harder to use diff tools. I need to go through the tox code to understand why it happens. So it is valuable to add information about the condition required to run a command from `list_dependencies_command`

2023-01-18 23:02 UTC, gaborbernat approved these changes

2023-01-18 23:29 UTC, gaborbernat approved these changes

2023-01-18 23:29 UTC, gaborbernat requested changes
You'll need to fix the CI.

2023-01-18 23:35 UTC, Czaki commented
I was creating this PR outside my main machine without pre-commit installed. Sorry for such stupid typos that block CI.

2023-01-19 01:24 UTC, gaborbernat approved these changes

2023-01-19 01:24 UTC, merged

2023-01-19 01:24 UTC, gaborbernat commented
No worries, all good.