Avoid race conditions in tests using the demo_pkg_inline fixture
tox-dev/tox pull request #2986
Opened 2023-04-13 09:39 UTC by hroncok

By using FileLock (already used as a dependency),
we ensure only one test uses the demo_pkg at a time.

This avoids race conditions happening with `pytest -n=auto`.

Fixes https://github.com/tox-dev/tox/issues/2985

# Thanks for contribution

Please, make sure you address all the checklists (for details on how see
[development documentation](http://tox.readthedocs.org/en/latest/development.html#development))!

- [x] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [x] ensured there are test(s) validating the fix (fix in tests)
- [x] added news fragment in `docs/changelog` folder
- [ ] updated/extended the documentation (not relevant)

2023-04-13 09:55 UTC, hroncok commented
Working on the typing fix. never understood why pytest fixtures are strongly typed, but will try to figure it out.

2023-04-13 09:56 UTC, hroncok commented
`tox -e type` now passed for me.

2023-04-13 18:29 UTC, gaborbernat requested changes
👍

2023-04-13 18:33 UTC, hroncok commented on tests/conftest.py
> +    with FileLock(str(demo_path) + ".lock"):
Amedned.

2023-04-13 18:53 UTC, merged

2023-04-13 19:22 UTC, hroncok commented
Belated idea: Should the lockfile be gitignored?

2023-04-19 19:35 UTC, hroncok commented
Do you prefer `*.lock` or this one only?

2023-04-19 20:03 UTC, gaborbernat commented
> this one only?

2023-04-19 20:06 UTC, hroncok commented
https://github.com/tox-dev/tox/pull/2988