fix(tox_env.python): do not process absolute paths to interpreter as PythonSpec
tox-dev/tox pull request #3311
Opened 2024-07-20 17:59 UTC by paveldikov

Fixes: #3191

- [X] ran the linter to address style issues (`tox -e fix`)
- [X] wrote descriptive pull request text
- [X] ensured there are test(s) validating the fix
- [X] added news fragment in `docs/changelog` folder
- [ ] updated/extended the documentation

---
© 2024 Morgan Stanley.

THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE APACHE LICENSE V.2.0.

THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

2024-07-26 15:52 UTC, gaborbernat requested changes

2024-07-26 15:52 UTC, gaborbernat commented on src/tox/tox_env/python/api.py
> +                if os.path.isabs(base_python):  # noqa: PTH117
use pathlib

2024-08-07 17:17 UTC, gaborbernat approved these changes
![](https://media.giphy.com/media/myRQnhrdKEryxF6xSK/giphy.gif)

2024-08-07 17:17 UTC, merged

2024-08-08 10:32 UTC, paveldikov commented
Thank you for making the changes and merging this! Sorry I have not had time recently to revisit this PR (`tox-uv` was necessary and sufficient for my own use case, so that's that 😊)