Ensure tox-created directories contain CACHEDIR.TAG
tox-dev/tox pull request #3342
Opened 2024-09-10 15:53 UTC by akx

This PR ensures that `.tox` subdirectories contain a `CACHEDIR.TAG` file, which can be used to exclude the directories from e.g. backups.

> [!NOTE]
> 
> With this implementation, the `.tox` directory itself won't contain the tag file, since there is no explicit `mkdir` call for the workdir. Only the subdirectories explicitly created by calls around Tox will be populated with the file.

Fixes #3334

- [x] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [ ] ensured there are test(s) validating the fix
- [ ] added news fragment in `docs/changelog` folder
- [ ] updated/extended the documentation

2024-09-10 15:59 UTC, gaborbernat requested changes
Why create these in sub folders? Why not just created it within the `.tox` root directory and be done with it?

2024-09-10 16:07 UTC, akx commented
> Why not just created it within the `.tox` root directory and be done with it?

I felt there was an idea behind the decision to not have an explicit call to create that directory – maybe that the workdir wouldn't be eagerly created before it's needed (just to hold a subdirectory).

> Just because there isn't does not mean we can't add it.

Sure, I'll do that. Would you prefer eagerly creating the workdir with the cache tag, or having the places that create those workdir subdirs ensure the workdir has the cache tag?

2024-09-10 16:37 UTC, gaborbernat commented
> having the places that create those workdir subdirs ensure the workdir has the cache tag

Probably this 🤔

2024-09-11 10:13 UTC, akx commented
> > having the places that create those workdir subdirs ensure the workdir has the cache tag
> 
> Probably this 🤔

It turned out a little trickier like that, since an user could point Tox to a pre-created workdir, which we then certainly do not want to litter with a `CACHEDIR.TAG` file.

I still didn't write tests for this incarnation, just in case you'd like to take a review look first.

2024-09-11 18:05 UTC, gaborbernat requested changes
The CI is fialing

2024-09-11 18:06 UTC, gaborbernat requested changes
Needs tests too 👍

2024-10-01 03:39 UTC, gaborbernat commented
@akx you still plan to finish this or should I close it?

2024-10-01 05:14 UTC, akx commented
> @akx you still plan to finish this or should I close it?

Yeah, it's still under construction – just been busy with work and figuring out how to best test-cover this. Rebased & added a commit that has some WIP tests :)

2024-10-14 17:06 UTC, gaborbernat commented
No worries, but note the CI is still failing 😊

2024-11-26 02:08 UTC, gaborbernat commented
@akx friendly bump here 👍

2024-11-27 17:42 UTC, closed without merging